### ISSUE TITLE
Выдавать строчку с ошибкой.

### ISSUE THREAD

**Issue by vladthelittleone** [HustleHardCode/spacecraft#149]
Выделяем строчку с ошибкой, задаем аннотацию.
Внизу пример, как задать код анотации + выделить строку.

``` css
  .bar{
    position:absolute;
    background:rgba(100,100,200,0.5);
    z-index:40
  }
```

``` javascript
    var editor = ace.edit("editor");
    editor.setTheme("ace/theme/chrome");
    editor.getSession().setMode("ace/mode/javascript");
    editor.session.setOption("useWorker", false);
    var Range = ace.require('ace/range').Range;
    // Выделяем код
    editor.session.addMarker(new Range(3, 0, 5, 0), "bar", "fullLine");
    // Задаем аннотацию
    editor.getSession().setAnnotations([{
      row: 1,
      column: 0,
      text: "Strange error",
      type: "error" // also warning and information
    }]);
```

Алсо https://groups.google.com/forum/#!topic/ace-discuss/joAFrXwWLX8
